# Generated by Django 6.0.2 on 2026-03-24 01:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertainly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('external_id', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
            ],
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='spotify_id',
            new_name='external_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='spotify_id',
            new_name='external_id',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='ticket_master_id',
            new_name='external_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='city',
        ),
        migrations.RemoveField(
            model_name='review',
            name='img_path',
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(to='concertainly.genre'),
        ),
        migrations.AddField(
            model_name='artist',
            name='image_src',
            field=models.CharField(default='https://static.vecteezy.com/system/resources/thumbnails/050/393/628/small/cute-curious-gray-and-white-kitten-in-a-long-shot-photo.jpg', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concertainly.venue'),
        ),
    ]
