# Generated by Django 6.0.2 on 2026-03-10 17:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertainly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
