# Generated by Django 6.0.2 on 2026-03-24 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertainly', '0002_venue_rename_spotify_id_artist_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='artist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='concertainly.artist'),
            preserve_default=False,
        ),
    ]
