# Generated by Django 6.0.2 on 2026-03-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concertainly', '0002_delete_concertuser'),
        ('concertainly', '0002_genre_rename_name_user_username'),
    ]

    operations = [
    ]
