# Generated by Django 6.0.2 on 2026-03-24 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concertainly', '0003_review_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='artist',
        ),
    ]
